export const EVENTS = {
  REMOVE_BLUEPRINT: 'remove blueprint',
  NEW_WEAPON_PLAYED: 'newWeaponPlayed',
  BLUEPRINT_PLAYED: 'blueprintPlayed',
  RESOURCE_PLAYED: 'resourcePlayed',
  DRAW_CARD: 'drawCard',
  PLAY_CARD: 'playCard',
  PLAYER_DIED: 'playerDied',
  HP_CHANGED: 'hpChanged',
  UPDATE_ENERGY: 'updateEnergy',
  ENERGY_CHANGED: 'energyChanged',
  BLUEPRINT_CHANGED: 'blueprintChanged',
  BLUEPRINT_ADDED: 'blueprintAdded',
  WEAPON_CHANGED: 'weaponChanged',
  WEAPON_ADDED: 'weaponAdded',
  WEAPON_REMOVED: 'weaponRemoved',
  ADD_CARD_TO_BOTTOM_OF_DECK: 'addCardToBottomOfDeck',
  NEW_BOT: 'newBot',
  BOT_DAMAGED: 'botDamaged',
  BOT_REMOVED: 'botRemoved',
  BOT_DESTROYED: 'botDestroyed',
  PROJECTILE_DESTROYED: 'projectileDestroyed',
  PROJECTILE_FIRED: 'projectileFired',
  PROJECTILE_FIRING: 'projectileFiring',
  CURRENT_PLAYERS: 'currentPlayers',
  CURRENT_BOTS: 'currentBots',
  CURRENT_STRUCTURES: 'currentStructures',
  NEW_PLAYER: 'newPlayer',
  PLAYER_MOVED: 'playerMoved',
  PLAYER_DAMAGED: 'playerDamaged',
  PLAYER_REMOVED: 'disconnect',
};
