export const EVENTS = {
  REMOVE_BLUEPRINT: 'remove blueprint',
  NEW_WEAPON_PLAYED: 'newWeaponPlayed',
  BLUEPRINT_PLAYED: 'blueprintPlayed',
  RESOURCE_PLAYED: 'resourcePlayed',
  DRAW_CARD: 'drawCard',
  PLAY_CARD: 'playCard',
  PLAYER_DIED: 'playerDied',
  HP_CHANGED: 'hpChanged',
  UPDATE_ENERGY: 'updateEnergy',
  ENERGY_CHANGED: 'energyChanged',
  BLUEPRINT_CHANGED: 'blueprintChanged',
  BLUEPRINT_ADDED: 'blueprintAdded',
  WEAPON_CHANGED: 'weaponChanged',
  WEAPON_ADDED: 'weaponAdded',
  WEAPON_REMOVED: 'weaponRemoved',
  ADD_CARD_TO_BOTTOM_OF_DECK: 'addCardToBottomOfDeck',
  BOT_DESTROYED: 'botDestroyed',
  PROJECTILE_FIRED: 'projectileFired',
};
